apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverspace-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: serverspace-pv
  storageClassName: ""
