apiVersion: v1
kind: PersistentVolume
metadata:
  name: serverspace-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.100
    path: /home/hunter/shared-space/ServerSpace
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
